
server:
  port: 8090
spring:
  application:
    name: gateway-service-api
  cloud:
    gateway:
      locator:
        discovery:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth-service-public
          uri: lb://AUTH-SERVICE-API
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: auth-service-secured
          uri: lb://AUTH-SERVICE-API
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter


        - id: shopping-service-api
          uri: lb://SHOPPING-SERVICE-API
          predicates:
            - Path=/api/shopping/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter


        - id: product-service-api
          uri: lb://PRODUCT-SERVICE-API
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter


        - id: order-service-api
          uri: lb://ORDER-SERVICE-API
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

        - id: payment-service-api
          uri: lb://PAYMENT-SERVICE-API
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

        - id: notification-service-api
          uri: lb://NOTIFICATION-SERVICE-API
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1


        - id: user-service-api-swagger
          uri: lb://USER-SERVICE-API
          predicates:
            - Path=/api/users/swagger-ui.html, /api/users/swagger-ui/**, /api/users/v3/api-docs
          filters:
            - StripPrefix=1

        - id: product-service-api-swagger
          uri: lb://PRODUCT-SERVICE-API
          predicates:
            - Path=/api/product/swagger-ui.html, /api/product/swagger-ui/**, /api/product/v3/api-docs
          filters:
            - StripPrefix=1

        - id: shopping-service-api-swagger
          uri: lb://SHOPPING-SERVICE-API
          predicates:
            - Path=/api/shopping/swagger-ui.html, /api/shopping/swagger-ui/**, /api/shopping/v3/api-docs
          filters:
            - StripPrefix=1

        - id: order-service-api-swagger
          uri: lb://ORDER-SERVICE-API
          predicates:
            - Path=/api/order/swagger-ui.html, /api/order/swagger-ui/**, /api/order/v3/api-docs
          filters:
            - StripPrefix=1

        - id: notification-service-api-swagger
          uri: lb://NOTIFICATION-SERVICE-API
          predicates:
            - Path=/api/notification/swagger-ui.html, /api/notification/swagger-ui/**, /api/notification/v3/api-docs
          filters:
            - StripPrefix=1
        
jwt:
  secret: 3E3U3HR23GR627GR27723RY23IJR923R2379HRRJK934
  expiration: 604800000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service-api:8761/eureka/